version: '2'
services:
  dockerapp:
    extends:
      file: common.yml
      service: dockerapp
    image: jleetutorial/dockerapp
    depends_on:
      - redis
  redis:
    extends:
      file: common.yml
      service: redis
